FROM node:18.12-slim

WORKDIR /app

# 安装 Cloudflare Workers CLI 工具
RUN npm install -g wrangler@2.15.0

ENV WRANGLER_SEND_METRICS=false
ENV OPENAI_GPT4=https://api.openai.com/v1
ENV OPENAI_GPT35_TURBO=https://api.openai.com/v1
ENV OPENAI_KEY4 = sk-xxx
ENV OPENAI_KEY35_TURBO = sk-xxx
ENV SHOULD_USE_OPENAI=1
ENV SHOULD_MAKE_LINE=1
ENV WEBHOOK_KEY=8610b5aa-0683-40bb-9a58-8910dfd26c49
ENV RUST_LOG=error

EXPOSE 8787

# 复制 Workers 脚本到镜像
COPY server.js .

# 启动本地开发服务器
CMD ["wrangler", "dev", "server.js", "--local", "--var", "OPENAI_GPT4:$OPENAI_GPT4", "OPENAI_KEY4:$OPENAI_KEY4", "OPENAI_GPT35_TURBO:$OPENAI_GPT35_TURBO", "OPENAI_KEY35_TURBO:$OPENAI_KEY35_TURBO", "SHOULD_USE_OPENAI:$SHOULD_USE_OPENAI", "SHOULD_MAKE_LINE:$SHOULD_MAKE_LINE", "WEBHOOK_KEY:$WEBHOOK_KEY" ,"--log-level", "$RUST_LOG"]
