name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 当main分支有新的commit时触发

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t xhtnext/mycf .
        docker push xhtnext/mycf
